
CREATE TABLE raw.client (
    uniqsubs INTEGER,
    actvsubs INTEGER,
    new_cell TEXT,
    crclscod TEXT,
    asl_flag TEXT,
    totcalls INTEGER,
    totmou NUMERIC,
    totrev NUMERIC,
    adjrev NUMERIC,
    adjmou NUMERIC,
    adjqty INTEGER,
    avgrev NUMERIC,
    avgmou NUMERIC,
    avgqty NUMERIC,
    avg3mou INTEGER,
    avg3qty INTEGER,
    avg3rev INTEGER,
    avg6mou NUMERIC,
    avg6qty NUMERIC,
    avg6rev NUMERIC,
    prizm_social_one TEXT,
    area TEXT,
    dualband TEXT,
    refurb_new TEXT,
    hnd_price NUMERIC,
    phones NUMERIC,
    models NUMERIC,
    hnd_webcap TEXT,
    truck NUMERIC,
    rv NUMERIC,
    ownrent TEXT,
    lor NUMERIC,
    dwlltype TEXT,
    marital TEXT,
    adults NUMERIC,
    infobase TEXT,
    income NUMERIC,
    numbcars NUMERIC,
    hhstatin TEXT,
    dwllsize TEXT,
    forgntvl NUMERIC,
    ethnic TEXT,
    kid0_2 TEXT,
    kid3_5 TEXT,
    kid6_10 TEXT,
    kid11_15 TEXT,
    kid16_17 TEXT,
    creditcd TEXT,
    eqpdays NUMERIC,
    customer_id INTEGER
);


DROP TABLE IF EXISTS raw.telco_services;

CREATE TABLE raw.telco_services (
    service_id VARCHAR(20),
    customer_id VARCHAR(20),
    count INTEGER,
    quarter VARCHAR(20),
    referred_a_friend VARCHAR(10),
    number_of_referrals INTEGER,
    tenure_in_months INTEGER,
    offer VARCHAR(50),
    phone_service VARCHAR(10),
    avg_monthly_long_distance_charges NUMERIC(10,2),
    multiple_lines VARCHAR(10),
    internet_service VARCHAR(10),
    internet_type VARCHAR(50),
    avg_monthly_gb_download INTEGER,
    online_security VARCHAR(10),
    online_backup VARCHAR(10),
    device_protection_plan VARCHAR(10),
    premium_tech_support VARCHAR(10),
    streaming_tv VARCHAR(10),
    streaming_movies VARCHAR(10),
    streaming_music VARCHAR(10),
    unlimited_data VARCHAR(10),
    contract VARCHAR(30),
    paperless_billing VARCHAR(10),
    payment_method VARCHAR(50),
    monthly_charge NUMERIC(10,2),
    total_charges NUMERIC(12,2),
    total_refunds NUMERIC(12,2),
    total_extra_data_charges INTEGER,
    total_long_distance_charges NUMERIC(12,2),
    total_revenue NUMERIC(12,2)
);

DROP TABLE IF EXISTS raw.telco_status;

CREATE TABLE raw.telco_status (
    status_id VARCHAR(20),
    customer_id VARCHAR(20),
    count INTEGER,
    quarter VARCHAR(20),
    satisfaction_score INTEGER,
    customer_status VARCHAR(30),
    churn_label VARCHAR(10),
    churn_value INTEGER,
    churn_score INTEGER,
    cltv INTEGER,
    churn_category VARCHAR(50),
    churn_reason TEXT
);

DROP TABLE IF EXISTS raw.record;

CREATE TABLE raw.record (
    rev_mean NUMERIC,
    mou_mean NUMERIC,
    totmrc_mean NUMERIC,
    da_mean NUMERIC,
    ovrmou_mean NUMERIC,
    ovrrev_mean NUMERIC,
    vceovr_mean NUMERIC,
    datovr_mean NUMERIC,
    roam_mean NUMERIC,
    change_mou NUMERIC,
    change_rev NUMERIC,
    drop_vce_mean NUMERIC,
    drop_dat_mean NUMERIC,
    blck_vce_mean NUMERIC,
    blck_dat_mean NUMERIC,
    unan_vce_mean NUMERIC,
    unan_dat_mean NUMERIC,
    plcd_vce_mean NUMERIC,
    plcd_dat_mean NUMERIC,
    recv_vce_mean NUMERIC,
    recv_sms_mean NUMERIC,
    comp_vce_mean NUMERIC,
    comp_dat_mean NUMERIC,
    custcare_mean NUMERIC,
    ccrndmou_mean NUMERIC,
    cc_mou_mean NUMERIC,
    inonemin_mean NUMERIC,
    threeway_mean NUMERIC,
    mou_cvce_mean NUMERIC,
    mou_cdat_mean NUMERIC,
    mou_rvce_mean NUMERIC,
    owylis_vce_mean NUMERIC,
    mouowylisv_mean NUMERIC,
    iwylis_vce_mean NUMERIC,
    mouiwylisv_mean NUMERIC,
    peak_vce_mean NUMERIC,
    peak_dat_mean NUMERIC,
    mou_peav_mean NUMERIC,
    mou_pead_mean NUMERIC,
    opk_vce_mean NUMERIC,
    opk_dat_mean NUMERIC,
    mou_opkv_mean NUMERIC,
    mou_opkd_mean NUMERIC,
    drop_blk_mean NUMERIC,
    attempt_mean NUMERIC,
    complete_mean NUMERIC,
    callfwdv_mean NUMERIC,
    callwait_mean NUMERIC,
    churn INTEGER,
    months INTEGER,
    customer_id INTEGER
);